<?php
require_once('PHPExcel.php');
require_once('PHPExcel/Writer/Excel2007.php');
require_once('include.excel.php');
require_once 'PHPExcel/IOFactory.php';
$myvar = unserialize($_POST["shownarr"]);

$objPHPExcel = new PHPExcel();

$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->getStyle('B1:L900')->getAlignment()->setWrapText(true);
$objPHPExcel->getActiveSheet()->setCellValue('A1' , 'NCT ID');
$objPHPExcel->getActiveSheet()->setCellValue('B1' , 'Title');
$objPHPExcel->getActiveSheet()->setCellValue('C1' , 'N');
$objPHPExcel->getActiveSheet()->setCellValue('D1' , 'Region');
$objPHPExcel->getActiveSheet()->setCellValue('E1' , 'Status');
$objPHPExcel->getActiveSheet()->setCellValue('F1' , 'Sponsor');
$objPHPExcel->getActiveSheet()->setCellValue('G1' , 'Conditions');
$objPHPExcel->getActiveSheet()->setCellValue('H1' , 'Interventions');
$objPHPExcel->getActiveSheet()->setCellValue('I1' , 'Start');
$objPHPExcel->getActiveSheet()->setCellValue('J1' , 'End');
$objPHPExcel->getActiveSheet()->setCellValue('K1' , 'Ph');
$objPHPExcel->getActiveSheet()->setCellValue('L1' , 'Result');

$i=2;



$bgcol="D5D3E6";
$styleThinBlueBorderOutline = array(
	'borders' => array(
		'outline' => array(
			'style' => PHPExcel_Style_Border::BORDER_THIN,
			'color' => array('argb' => 'FF0000FF'),
		),
	),
);
foreach ($myvar as $key=>$value)
{
	$objPHPExcel->getProperties()->setCreator("The Larvol Group")
								 ->setLastModifiedBy("TLG")
								 ->setTitle("Larvol Trials")
								 ->setSubject("Larvol Trials")
								 ->setDescription("Excel file generated by Larvol Trials")
								 ->setKeywords("Larvol Trials")
								 ->setCategory("Clinical Trials");
	$objPHPExcel->getActiveSheet()->getStyle('A' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('B' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('C' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('D' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('E' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('F' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('G' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('G' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('H' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('H' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('I' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('I' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('J' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('J' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('K' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('K' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('L' . ($i-1))->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->getStyle('L' . $i)->applyFromArray($styleThinBlueBorderOutline);
	$objPHPExcel->getActiveSheet()->setCellValue('A' . $i, 'NCT' . sprintf("%08s",$value["NCT.nct_id"]));
	$objPHPExcel->getActiveSheet()->setCellValue('B' . $i, $value["NCT.brief_title"]);
	$objPHPExcel->getActiveSheet()->getCell('B' . $i)->getHyperlink()->setUrl('http://clinicaltrials.gov/ct2/show/'. $objPHPExcel->getActiveSheet()->getCell('A' . $i)->getValue() );
	$objPHPExcel->getActiveSheet()->getCell('B' . $i)->getHyperlink()->setTooltip('Navigate to website');
	$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
	if(isset($value["NCT.enrollment"])) 				$objPHPExcel->getActiveSheet()->setCellValue('C' . $i, $value["NCT.enrollment"]);
														$objPHPExcel->getActiveSheet()->setCellValue('D' . $i, "");
	if(isset($value["NCT.overall_status"])) 			$objPHPExcel->getActiveSheet()->setCellValue('E' . $i, $value["NCT.overall_status"]);
	if(isset($value["NCT.lead_sponsor"])) 				$objPHPExcel->getActiveSheet()->setCellValue('F' . $i, $value["NCT.lead_sponsor"]);
	if(isset($value["NCT.condition"])) 					$objPHPExcel->getActiveSheet()->setCellValue('G' . $i, $value["NCT.condition"]);
	if(isset($value["NCT.intervention_name"])) 			$objPHPExcel->getActiveSheet()->setCellValue('H' . $i, $value["NCT.intervention_name"]);
	if(isset($value["NCT.start_date"])) 				$objPHPExcel->getActiveSheet()->setCellValue('I' . $i, $value["NCT.start_date"]);
	if(isset($value["NCT.primary_completion_date"])) 	$objPHPExcel->getActiveSheet()->setCellValue('J' . $i, $value["NCT.primary_completion_date"]);
	if(isset($value["NCT.phase"])) 						$objPHPExcel->getActiveSheet()->setCellValue('K' . $i, $value["NCT.phase"]);
														$objPHPExcel->getActiveSheet()->setCellValue('L' . $i, "");
	if($bgcol=="D5D3E6") $bgcol="EDEAFF"; 	else $bgcol="D5D3E6";
	
	$objPHPExcel->getActiveSheet()->getStyle('A' . $i .':J' .$i )->applyFromArray
		(
			array
			(
				'fill' => array
				(
					'type'       => PHPExcel_Style_Fill::FILL_SOLID,
					'rotation'   => 0,
					'startcolor' => array
					(
						'rgb' => $bgcol
					),
					'endcolor'   => array
					(
						'rgb' => $bgcol
					)
				)
			)
		);
		
	$objPHPExcel->getActiveSheet()->getStyle('L' . $i )->applyFromArray
		(
			array
			(
				'fill' => array
				(
					'type'       => PHPExcel_Style_Fill::FILL_SOLID,
					'rotation'   => 0,
					'startcolor' => array
					(
						'rgb' => $bgcol
					),
					'endcolor'   => array
					(
						'rgb' => $bgcol
					)
				)
			)
		);
		
		
	
	$objPHPExcel->getActiveSheet()->getStyle('A1:L1')->applyFromArray
	(
		array
		(
			'font'    => array
			(
				'bold'      => true
			),
			'alignment' => array
			(
				'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
			),
			'borders' => array
			(
				'top'     => array
				(
 					'style' => PHPExcel_Style_Border::BORDER_THIN
 				)
			),
			'fill' => array
			(
	 			'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
	  			'rotation'   => 90,
	 			'startcolor' => array
				(
	 				'argb' => 'FFA0A0A0'
	 			),
	 			'endcolor'   => array
				(
	 				'argb' => 'FFFFFFFF'
	 			)
	 		)
		)
	);

	if(
		isset($value["NCT.overall_status"]) and 
		(
			$value["NCT.overall_status"]=="Completed" or 
			$value["NCT.overall_status"]=="Approved for marketing" or 
			$value["NCT.overall_status"]=="Temporarily not available" or 
			$value["NCT.overall_status"]=="No Longer Available" or 
			$value["NCT.overall_status"]=="Withdrawn" or 
			$value["NCT.overall_status"]=="Terminated" or 
			$value["NCT.overall_status"]=="Suspended" or 
			$value["NCT.overall_status"]=="Completed"
		)
	)	$objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':L' . $i)->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_RED);

	if(isset($value["NCT.phase"]) and $value["NCT.phase"]=="Phase 1")
	{
	
		$objPHPExcel->getActiveSheet()->getStyle('K' . $i )->applyFromArray
		(
			array
			(
				'fill' => array
				(
					'type'       => PHPExcel_Style_Fill::FILL_SOLID,
					'rotation'   => 0,
					'startcolor' => array
					(
						'rgb' => '99CC00'
					),
					'endcolor'   => array
					(
						'rgb' => '99CC00'
					)
				)
			)
		);
	
	
	}
	if(isset($value["NCT.phase"]) and $value["NCT.phase"]=="Phase 2")
	{
	
		$objPHPExcel->getActiveSheet()->getStyle('K' . $i )->applyFromArray
		(
			array
			(
				'fill' => array
				(
					'type'       => PHPExcel_Style_Fill::FILL_SOLID,
					'rotation'   => 0,
					'startcolor' => array
					(
						'rgb' => 'FFFF00'
					),
					'endcolor'   => array
					(
						'rgb' => 'FFFF00'
					)
				)
			)
		);
	
	
	}
	
	if(isset($value["NCT.phase"]) and $value["NCT.phase"]=="Phase 3")
	{
	
		$objPHPExcel->getActiveSheet()->getStyle('K' . $i )->applyFromArray
		(
			array
			(
				'fill' => array
				(
					'type'       => PHPExcel_Style_Fill::FILL_SOLID,
					'rotation'   => 0,
					'startcolor' => array
					(
						'rgb' => 'FF9900'
					),
					'endcolor'   => array
					(
						'rgb' => 'FF9900'
					)
				)
			)
		);
	
	
	}

	if(isset($value["NCT.phase"]) and $value["NCT.phase"]=="Phase 4")
	{
	
		$objPHPExcel->getActiveSheet()->getStyle('K' . $i )->applyFromArray
		(
			array
			(
				'fill' => array
				(
					'type'       => PHPExcel_Style_Fill::FILL_SOLID,
					'rotation'   => 0,
					'startcolor' => array
					(
						'rgb' => 'FF0000'
					),
					'endcolor'   => array
					(
						'rgb' => 'FF0000'
					)
				)
			)
		);
	
	
	}
	$i++;
}

$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(13);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(35);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(5);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(12);
$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(25);
$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(35);
$objPHPExcel->getActiveSheet()->getColumnDimension('I')->setWidth(12);
$objPHPExcel->getActiveSheet()->getColumnDimension('J')->setWidth(12);
$objPHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(9);
$objPHPExcel->getActiveSheet()->getColumnDimension('L')->setAutoSize(true);
$objPHPExcel->getActiveSheet()->getStyle('B1:L900')->getAlignment()->setWrapText(true);
$objPHPExcel->getActiveSheet()->getStyle('A1:L200')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_TOP);
$objPHPExcel->getActiveSheet()->setCellValue('A1' , 'NCT ID');
$objPHPExcel->getActiveSheet()->setTitle('Larvol Trials');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setName('Calibri');
$objPHPExcel->setActiveSheetIndex(0);
$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);

ob_end_clean(); 

header("Pragma: public");
header("Expires: Sat, 26 Jul 1997 05:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: no-cache, must-revalidate, post-check=0, pre-check=0");
header("Content-Type: application/force-download");
header("Content-Type: application/download");
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="  DTT  _' . date('Y-m-d_H.i.s') . '.xlsx"');
header("Content-Transfer-Encoding: binary ");
$objWriter->save('php://output');
@flush();
exit;

?>